# Generated by Django 3.1.2 on 2021-05-26 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compliments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliment', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('person', models.IntegerField(choices=[(1, 'Nate'), (0, 'Annie')], default=0)),
                ('category', models.IntegerField(choices=[(0, 'Anytime'), (1, 'Morning'), (2, 'Afternoon'), (3, 'Evening')], default=0)),
            ],
        ),
    ]
