# Generated by Django 3.1.2 on 2021-05-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliments',
            name='person',
            field=models.CharField(max_length=10),
        ),
    ]
