# Generated by Django 3.1.2 on 2021-05-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliments', '0003_auto_20210525_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliments',
            name='created',
        ),
        migrations.AlterField(
            model_name='compliments',
            name='compliment',
            field=models.CharField(max_length=75),
        ),
    ]
