# Generated by Django 3.1.2 on 2021-05-26 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compliments', '0004_auto_20210525_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
