# Generated by Django 3.1.2 on 2021-05-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliments', '0005_compliments_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliments',
            name='category',
            field=models.CharField(choices=[('anytime', 'Anytime'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='anytime', max_length=20),
        ),
    ]
