# Generated by Django 3.1.2 on 2020-10-09 12:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('time_began', models.DateTimeField(default=datetime.datetime(2020, 10, 9, 7, 50, 57, 604308))),
                ('time_ended', models.DateTimeField(default=datetime.datetime(2020, 10, 9, 7, 50, 57, 604308))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
