# Generated by Django 3.1.2 on 2020-10-11 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_began',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 21, 26, 24, 102782)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
