# Generated by Django 3.1.2 on 2020-10-11 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_auto_20201010_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='task',
            name='time_began',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 0, 27, 33, 853006)),
        ),
    ]
