# Generated by Django 3.1.2 on 2020-10-11 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0005_auto_20201011_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_began',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 9, 42, 1, 712149)),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
