# Generated by Django 3.1.2 on 2020-10-11 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0007_auto_20201011_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_began',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 11, 15, 4, 955410)),
        ),
    ]
