# Generated by Django 3.1.2 on 2020-10-14 02:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0009_auto_20201012_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_began',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 13, 21, 28, 30, 30898)),
        ),
        migrations.CreateModel(
            name='TaskRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_status', models.CharField(choices=[('child', 'Child'), ('parent', 'Parent')], max_length=50)),
                ('current_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_task', to='to_do_list.task')),
                ('target_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_task', to='to_do_list.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='relationships',
            field=models.ManyToManyField(related_name='_task_relationships_+', through='to_do_list.TaskRelationship', to='to_do_list.Task'),
        ),
    ]
