# Generated by Django 3.1.2 on 2020-10-14 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0010_auto_20201013_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='relationships',
            field=models.ManyToManyField(related_name='relations', through='to_do_list.TaskRelationship', to='to_do_list.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_began',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 15, 7, 34, 746881)),
        ),
    ]
