# Generated by Django 3.1.2 on 2020-10-14 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0012_auto_20201014_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_began',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 15, 21, 51, 851101)),
        ),
    ]
