# Generated by Django 3.1.2 on 2020-10-18 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0014_auto_20201017_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', 'priority', 'title']},
        ),
        migrations.AlterField(
            model_name='task',
            name='time_began',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 18, 17, 26, 55, 140913)),
        ),
    ]
