# Generated by Django 3.1.2 on 2020-10-18 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0015_auto_20201018_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_began',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
