# Generated by Django 3.1.2 on 2020-10-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0016_auto_20201018_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='taskrelationship',
            name='relationship_status',
            field=models.CharField(choices=[('after_task', 'Current task can be done after '), ('before_task', 'Current task must be done before ')], max_length=50),
        ),
    ]
