# Generated by Django 3.1.2 on 2020-10-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0018_auto_20201020_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrelationship',
            name='relationship_status',
            field=models.CharField(choices=[('after_task', 'Current task can be done after '), ('before_task', 'Current task must be done before '), ('project', 'project')], max_length=50),
        ),
    ]
