# Generated by Django 3.1.2 on 2020-10-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0021_auto_20201027_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
