# Generated by Django 3.1.2 on 2020-10-27 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0022_auto_20201027_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrelationship',
            name='project',
        ),
    ]
