# Generated by Django 3.1.2 on 2020-10-27 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0023_remove_taskrelationship_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='to_do_list.project'),
        ),
        migrations.AlterField(
            model_name='taskrelationship',
            name='relationship_status',
            field=models.CharField(choices=[('after_task', 'Current task can be done after '), ('before_task', 'Current task must be done before ')], max_length=50),
        ),
    ]
