# Generated by Django 3.1.2 on 2020-12-29 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('to_do_list', '0026_auto_20201103_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title', 'time_began']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed', 'project', 'priority', 'title']},
        ),
        migrations.AlterField(
            model_name='project',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
