# Generated by Django 3.1.2 on 2020-12-29 03:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.IntegerField()),
                ('activity', models.IntegerField(choices=[(1, 'sedentary'), (2, 'aerobic'), (3, 'weights')])),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('gender', models.IntegerField(choices=[(1, 'male'), (0, 'female')])),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neck', models.DecimalField(decimal_places=2, max_digits=4)),
                ('arm', models.DecimalField(decimal_places=2, max_digits=4)),
                ('wrist', models.DecimalField(decimal_places=2, max_digits=4)),
                ('waist', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hip', models.DecimalField(decimal_places=2, max_digits=4)),
                ('thigh', models.DecimalField(decimal_places=2, max_digits=4)),
                ('calf', models.DecimalField(decimal_places=2, max_digits=4)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
