# Generated by Django 3.1.2 on 2020-12-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psmf_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='activity',
            field=models.IntegerField(choices=[(1, 'sedentary'), (2, 'aerobic'), (3, 'weights')], default=1),
        ),
        migrations.AlterField(
            model_name='stats',
            name='gender',
            field=models.IntegerField(choices=[(1, 'male'), (0, 'female')], default=0),
        ),
    ]
